import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.IgnoreEmptyDirectories
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Generates the screenshotTest wrappers for the previews annotated with `@ScreenshotTest`.
 *
 * It reads the Kotlin sources instead of the compiled classes, so it doesn't depend on compiling main.
 * Each suite becomes a `<Suite>ScreenshotTests` class with one `@PreviewTest` function per preview, named after it.
 * Previews with `@PreviewLightDark` or a night `uiMode` get a dark `@Preview` too, next to or instead of the light one.
 */
@CacheableTask
abstract class GenerateScreenshotTestsTask : DefaultTask() {

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:IgnoreEmptyDirectories
    abstract val sources: ConfigurableFileCollection

    /** Package of the generated test classes. */
    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val previews = sources.files.sortedBy { it.path }.flatMap { parsePreviews(it) }
        val errors = previews.groupBy { it.suite to it.name }
            .filterValues { it.size > 1 }
            .map { (key, duplicates) ->
                "Duplicated preview name ${key.second} in suite ${key.first}: ${duplicates.joinToString { it.fqName }}"
            }
        if (errors.isNotEmpty()) throw GradleException(errors.joinToString("\n"))

        val packageDir = outputDir.get().asFile.resolve(packageName.get().replace('.', '/'))
        packageDir.deleteRecursively()
        packageDir.mkdirs()
        SUITES.forEach { suite ->
            val className = "${suite}ScreenshotTests"
            packageDir.resolve("$className.kt").writeText(
                generateSuite(className, previews.filter { it.suite == suite }.sortedBy { it.name })
            )
        }
    }

    private fun parsePreviews(file: File): List<AnnotatedPreview> {
        val source = file.readText()
        val annotations = ANNOTATION_REGEX.findAll(source).toList()
        if (annotations.isEmpty()) return emptyList()

        val packageName = PACKAGE_REGEX.find(source)?.groupValues?.get(1).orEmpty()
        return annotations.map { annotation ->
            val line = source.substring(0, annotation.range.first).count { it == '\n' } + 1
            fun fail(reason: String): Nothing = throw GradleException("${file.path}:$line: $reason")

            val args = annotation.groupValues[1]
            val suite = SUITE_REGEX.matchEntire(args)?.groupValues?.get(1)
                ?.takeIf { it in SUITES }
                ?: fail("@ScreenshotTest needs one of ${SUITES.joinToString { "ScreenshotSuite.$it" }}, found '$args'")
            val function = FUNCTION_REGEX.find(source, annotation.range.last + 1)
                ?: fail("@ScreenshotTest must annotate a function")
            val modifiers = source.substring(annotation.range.last + 1, function.range.first)
            if (modifiers.contains(Regex("""\bprivate\b"""))) {
                fail("@ScreenshotTest preview ${function.groupValues[1]} can't be private, make it internal")
            }
            if (function.groupValues[2].isNotBlank()) {
                fail("@ScreenshotTest preview ${function.groupValues[1]} can't have parameters")
            }
            val previewAnnotations = PREVIEW_REGEX.findAll(modifiers).map { it.groupValues[1] }.toList()
            val lightDark = modifiers.contains("@PreviewLightDark")
            val dark = lightDark || previewAnnotations.any { it.contains("UI_MODE_NIGHT_YES") }
            val light = lightDark || previewAnnotations.any { !it.contains("UI_MODE_NIGHT_YES") } || !dark
            AnnotatedPreview(
                suite = suite,
                light = light,
                dark = dark,
                name = function.groupValues[1],
                fqName = listOf(packageName, function.groupValues[1]).filter { it.isNotEmpty() }.joinToString("."),
            )
        }
    }

    private fun generateSuite(className: String, previews: List<AnnotatedPreview>): String = buildString {
        appendLine("// Generated by ${this@GenerateScreenshotTestsTask.name} from the @ScreenshotTest previews. Don't edit.")
        appendLine("package ${packageName.get()}")
        appendLine()
        appendLine("import android.content.res.Configuration")
        appendLine("import androidx.compose.runtime.Composable")
        appendLine("import androidx.compose.ui.tooling.preview.Preview")
        appendLine("import com.android.tools.screenshot.PreviewTest")
        appendLine()
        appendLine("class $className {")
        previews.forEach { preview ->
            appendLine()
            if (preview.light) appendLine("    @Preview(locale = \"es\")")
            if (preview.dark) {
                appendLine("    @Preview(locale = \"es\", uiMode = Configuration.UI_MODE_NIGHT_YES or Configuration.UI_MODE_TYPE_NORMAL)")
            }
            appendLine("    @PreviewTest")
            appendLine("    @Composable")
            appendLine("    fun ${preview.name}() {")
            appendLine("        ${preview.fqName}()")
            appendLine("    }")
        }
        appendLine("}")
    }

    private data class AnnotatedPreview(
        val suite: String,
        val light: Boolean,
        val dark: Boolean,
        val name: String,
        val fqName: String,
    )

    private companion object {
        val SUITES = listOf("Components", "Screens")
        val ANNOTATION_REGEX = Regex("""^[ \t]*@ScreenshotTest\(([^)]*)\)""", RegexOption.MULTILINE)
        val SUITE_REGEX = Regex("""\s*(?:suite\s*=\s*)?(?:ScreenshotSuite\.)?(\w+)\s*""")
        val FUNCTION_REGEX = Regex("""\bfun\s+(\w+)\s*\(([^)]*)\)""")
        val PREVIEW_REGEX = Regex("""@Preview\b(\([^)]*\))?""")
        val PACKAGE_REGEX = Regex("""^package\s+([\w.]+)""", RegexOption.MULTILINE)
    }
}
