import org.gradle.api.GradleException

/**
 * Pure logic behind [GenerateScreenshotTestsTask] and [OrphanScreenshotReferencesTask], without file access.
 */
internal object ScreenshotTestsGenerator {

    val SUITES = listOf("Components", "Screens")

    // The plugin names each reference <test>_<hash of the @Preview parameters>_<index>.png.
    // Changing these annotations changes the hashes, update them with the new reference file names.
    const val LIGHT_PREVIEW = """@Preview(locale = "es")"""
    const val LIGHT_HASH = "b2db1d68"
    const val DARK_PREVIEW =
        """@Preview(locale = "es", uiMode = Configuration.UI_MODE_NIGHT_YES or Configuration.UI_MODE_TYPE_NORMAL)"""
    const val DARK_HASH = "f6f1fda3"

    private val ANNOTATION_REGEX = Regex("""^[ \t]*@ScreenshotTest\(([^)]*)\)""", RegexOption.MULTILINE)
    private val SUITE_REGEX = Regex("""\s*(?:suite\s*=\s*)?(?:ScreenshotSuite\.)?(\w+)\s*""")
    private val FUNCTION_REGEX = Regex("""\bfun\s+(\w+)\s*\(([^)]*)\)""")
    // Each annotation runs until the next one, so a ")" inside a string argument doesn't cut it short
    private val ANNOTATION_START = Regex("""(?=@)""")
    private val PREVIEW_REGEX = Regex("""^@Preview\b""")
    private val PACKAGE_REGEX = Regex("""^package\s+([\w.]+)""", RegexOption.MULTILINE)
    private val INDEX_SUFFIX = Regex("""_\d+\.png$""")

    data class AnnotatedPreview(
        val suite: String,
        val light: Boolean,
        val dark: Boolean,
        val name: String,
        val fqName: String,
    )

    /** Finds the `@ScreenshotTest` previews in a Kotlin [source]. [path] is only used in error messages. */
    fun parsePreviews(source: String, path: String): List<AnnotatedPreview> {
        val annotations = ANNOTATION_REGEX.findAll(source).toList()
        if (annotations.isEmpty()) return emptyList()

        val packageName = PACKAGE_REGEX.find(source)?.groupValues?.get(1).orEmpty()
        return annotations.map { annotation ->
            val line = source.substring(0, annotation.range.first).count { it == '\n' } + 1
            fun fail(reason: String): Nothing = throw GradleException("$path:$line: $reason")

            val args = annotation.groupValues[1]
            val suite = SUITE_REGEX.matchEntire(args)?.groupValues?.get(1)
                ?.takeIf { it in SUITES }
                ?: fail("@ScreenshotTest needs one of ${SUITES.joinToString { "ScreenshotSuite.$it" }}, found '$args'")
            val function = FUNCTION_REGEX.find(source, annotation.range.last + 1)
                ?: fail("@ScreenshotTest must annotate a function")
            val modifiers = source.substring(annotation.range.last + 1, function.range.first)
            if (modifiers.contains(Regex("""\bprivate\b"""))) {
                fail("@ScreenshotTest preview ${function.groupValues[1]} can't be private, make it internal")
            }
            if (function.groupValues[2].isNotBlank()) {
                fail("@ScreenshotTest preview ${function.groupValues[1]} can't have parameters")
            }
            val previewAnnotations = modifiers.split(ANNOTATION_START).filter { PREVIEW_REGEX.containsMatchIn(it) }
            val lightDark = modifiers.contains("@PreviewLightDark")
            val dark = lightDark || previewAnnotations.any { it.contains("UI_MODE_NIGHT_YES") }
            val light = lightDark || previewAnnotations.any { !it.contains("UI_MODE_NIGHT_YES") } || !dark
            AnnotatedPreview(
                suite = suite,
                light = light,
                dark = dark,
                name = function.groupValues[1],
                fqName = listOf(packageName, function.groupValues[1]).filter { it.isNotEmpty() }.joinToString("."),
            )
        }
    }

    /** Fails if two previews of the same suite share a name, since the test names would clash. */
    fun checkDuplicates(previews: List<AnnotatedPreview>) {
        val errors = previews.groupBy { it.suite to it.name }
            .filterValues { it.size > 1 }
            .map { (key, duplicates) ->
                "Duplicated preview name ${key.second} in suite ${key.first}: ${duplicates.joinToString { it.fqName }}"
            }
        if (errors.isNotEmpty()) throw GradleException(errors.joinToString("\n"))
    }

    fun className(suite: String) = "${suite}ScreenshotTests"

    /** Source of the `<Suite>ScreenshotTests` class, with the [previews] of that suite. */
    fun generateSuite(packageName: String, suite: String, previews: List<AnnotatedPreview>, generatedBy: String): String =
        buildString {
            appendLine("// Generated by $generatedBy from the @ScreenshotTest previews. Don't edit.")
            appendLine("package $packageName")
            appendLine()
            appendLine("import android.content.res.Configuration")
            appendLine("import androidx.compose.runtime.Composable")
            appendLine("import androidx.compose.ui.tooling.preview.Preview")
            appendLine("import com.android.tools.screenshot.PreviewTest")
            appendLine()
            appendLine("class ${className(suite)} {")
            previews.filter { it.suite == suite }.sortedBy { it.name }.forEach { preview ->
                appendLine()
                if (preview.light) appendLine("    $LIGHT_PREVIEW")
                if (preview.dark) appendLine("    $DARK_PREVIEW")
                appendLine("    @PreviewTest")
                appendLine("    @Composable")
                appendLine("    fun ${preview.name}() {")
                appendLine("        ${preview.fqName}()")
                appendLine("    }")
            }
            appendLine("}")
        }

    /** Reference images the generated tests expect, as `<package path>/<class>/<test>_<hash>`. */
    fun expectedReferences(packageName: String, previews: List<AnnotatedPreview>): List<String> =
        SUITES.flatMap { suite ->
            val classPath = "${packageName.replace('.', '/')}/${className(suite)}"
            previews.filter { it.suite == suite }.sortedBy { it.name }.flatMap { preview ->
                listOfNotNull(
                    "$classPath/${preview.name}_$LIGHT_HASH".takeIf { preview.light },
                    "$classPath/${preview.name}_$DARK_HASH".takeIf { preview.dark },
                )
            }
        }

    /**
     * Reference images no generated test uses.
     * [referencePaths] are relative to the reference directory, with `/` separators.
     */
    fun findOrphans(expected: Set<String>, referencePaths: List<String>): List<String> =
        referencePaths
            .filter { it.endsWith(".png") }
            .filter { it.replace(INDEX_SUFFIX, "") !in expected }
            .sorted()
}
