name: Run Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Create secret.properties
      run: echo "MAPS_API_KEY=dummy_key" > secret.properties
    - name: Create google-services.json
      run: |
        cat > app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "123456789",
            "project_id": "dummy-project"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:123456789:android:dummy1",
                "android_client_info": {
                  "package_name": "com.sloy.sevibus"
                }
              }
            },
            {
              "client_info": {
                "mobilesdk_app_id": "1:123456789:android:dummy2", 
                "android_client_info": {
                  "package_name": "com.sloy.sevibus.debug"
                }
              }
            }
          ]
        }
        EOF
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        cache-read-only: false
    - name: Run tests
      run: ./gradlew test